CREATE TABLE D_DATE (
    ID_DATE  BIGSERIAL     NOT NULL PRIMARY KEY,
    DT_DATE  DATE        NOT NULL,
    DT_DAY   INTEGER NOT NULL,
    DT_MONTH INTEGER NOT NULL,
    DT_YEAR  INTEGER NOT NULL
);
