CREATE TABLE D_PUBLISHER (
    ID_PUBLISHER BIGSERIAL      NOT NULL PRIMARY KEY,
    NM_PUBLISHER VARCHAR (100)  NOT NULL,
    CD_STATUS    VARCHAR (50)   NOT NULL,
    LINDATE      DATE           NOT NULL,
    LINSOURCE    VARCHAR (50)   NOT NULL
);
