CREATE TABLE F_GAMESBYPLATFORM (
    ID_DATE            INTEGER    REFERENCES D_DATE (ID_DATE)  NOT NULL,
    ID_PUBLISHER       INTEGER    REFERENCES D_PUBLISHER (ID_PUBLISHER)  NOT NULL,
    ID_PLATFORM        INTEGER    REFERENCES D_PLATFORM (ID_PLATFORM) NOT NULL ,
    ID_GAME            INTEGER    REFERENCES D_GAMES (ID_GAME)  NOT NULL,
    ID_GENRE           INTEGER    REFERENCES D_GENRE (ID_GENRE)  NOT NULL,
    QT_GAMESBYPLATFORM INTEGER    NOT NULL,
    NR_CRITICSCORE     INTEGER    NOT NULL,
    NR_USERSCORE       INTEGER    NOT NULL,
    QT_GLOBALSALES     INTEGER NOT NULL,
    LINDATE            DATE           NOT NULL,
    LINSOURCE          VARCHAR (50)   NOT NULL
);
